export const bookDetailPage = {
  eyebrow: "Buch",
  inSeries: "In der Reihe",
  metadata: "Bibliografische Daten",
  description: "Beschreibung",
  series: "Reihe",
  author: "Autor",
  translator: "Übersetzung",
  editor: "Herausgeber",
  pages: "Seiten",
  format: "Format",
  language: "Sprache",
  publicationDate: "Erscheinung",
  status: "Status",
  price: "Preis",
  stockStatus: "Bestellstatus",
  availabilityTitle: "Verfügbarkeit",
  availabilityReady: "Direkt bestellbar",
  secondaryAction: "Reihe ansehen",
  documentsTitle: "Dokumente",
  sampleTitle: "Leseprobe",
  sampleAction: "Leseprobe herunterladen (PDF)",
  sampleMissing: "Leseprobe folgt in einer späteren Ausbaustufe.",
  editorialSheetTitle: "Ficha editorial",
  editorialSheetAction: "Ficha editorial herunterladen (PDF)",
  relatedTitle: "Weitere Titel der Reihe",
};
