export const bookDetailPage = {
  eyebrow: "Buch",
  inSeries: "In der Reihe",
  metadata: "Bibliografische Daten",
  description: "Beschreibung",
  series: "Reihe",
  author: "Autor",
  translator: "Uebersetzung",
  editor: "Herausgeber",
  pages: "Seiten",
  format: "Format",
  language: "Sprache",
  publicationDate: "Erscheinung",
  status: "Status",
  price: "Preis",
  stockStatus: "Bestellstatus",
  availabilityTitle: "Verfuegbarkeit",
  availabilityReady: "Sofort verfuegbar",
  secondaryAction: "Reihe ansehen",
  sampleTitle: "Leseprobe",
  sampleAction: "Leseprobe herunterladen (PDF)",
  sampleMissing: "Leseprobe folgt in einer spaeteren Ausbaustufe.",
  relatedTitle: "Weitere Titel der Reihe",
};
