export const bookDetailPage = {
  eyebrow: "Libro",
  inSeries: "En la coleccion",
  metadata: "Datos bibliograficos",
  description: "Descripcion",
  series: "Coleccion",
  author: "Autor",
  translator: "Traduccion",
  editor: "Edicion",
  pages: "Paginas",
  format: "Formato",
  language: "Idioma",
  publicationDate: "Publicacion",
  status: "Estado",
  price: "Precio",
  stockStatus: "Estado de pedido",
  availabilityTitle: "Disponibilidad",
  availabilityReady: "Disponible",
  secondaryAction: "Ver coleccion",
  sampleTitle: "Muestra",
  sampleAction: "Descargar muestra (PDF)",
  sampleMissing: "La muestra de lectura se incorporara en una fase posterior.",
  relatedTitle: "Otros titulos de la coleccion",
};
