export const bookDetailPage = {
  eyebrow: "Libro",
  inSeries: "En la colección",
  metadata: "Datos bibliográficos",
  description: "Descripción",
  series: "Colección",
  author: "Autor",
  translator: "Traducción",
  editor: "Edición",
  pages: "Páginas",
  format: "Formato",
  language: "Idioma",
  publicationDate: "Publicación",
  status: "Estado",
  price: "Precio",
  stockStatus: "Estado de pedido",
  availabilityTitle: "Disponibilidad",
  availabilityReady: "Compra directa disponible",
  secondaryAction: "Ver colección",
  documentsTitle: "Documentos",
  sampleTitle: "Muestra",
  sampleAction: "Descargar muestra (PDF)",
  sampleMissing: "La muestra de lectura se incorporará en una fase posterior.",
  editorialSheetTitle: "Ficha editorial",
  editorialSheetAction: "Descargar ficha editorial (PDF)",
  relatedTitle: "Otros títulos de la colección",
};
