create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  payment_provider text not null default 'wompi',
  provider_reference text not null unique,
  provider_transaction_id text,
  customer_email text,
  customer_name text,
  amount_total integer,
  currency text,
  payment_status text not null,
  payment_method_type text,
  shipping_address jsonb,
  provider_payload jsonb,
  order_status text not null default 'paid',
  locale text not null default 'de',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  book_slug text not null,
  book_title text not null,
  quantity integer not null default 1,
  unit_price integer,
  currency text,
  created_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'stripe_checkout_session_id'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'provider_reference'
  ) then
    alter table public.orders
      rename column stripe_checkout_session_id to provider_reference;
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'stripe_payment_intent_id'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'orders'
      and column_name = 'provider_transaction_id'
  ) then
    alter table public.orders
      rename column stripe_payment_intent_id to provider_transaction_id;
  end if;
end $$;

alter table public.orders
  add column if not exists payment_provider text not null default 'wompi',
  add column if not exists provider_reference text,
  add column if not exists provider_transaction_id text,
  add column if not exists payment_method_type text,
  add column if not exists shipping_address jsonb,
  add column if not exists provider_payload jsonb;

update public.orders
set payment_provider = 'wompi'
where payment_provider is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'orders_provider_reference_key'
  ) then
    alter table public.orders
      add constraint orders_provider_reference_key unique (provider_reference);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'order_items_order_id_book_slug_key'
  ) then
    alter table public.order_items
      add constraint order_items_order_id_book_slug_key unique (order_id, book_slug);
  end if;
end $$;
